# Generated by Django 5.0 on 2023-12-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_exercise_answer_a_en_exercise_answer_a_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='topic_en',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='topic_ru',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='topic_uz',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='variant_en',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='variant_ru',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='variant_uz',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user_ru',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user_uz',
        ),
        migrations.RemoveField(
            model_name='result',
            name='variant_en',
        ),
        migrations.RemoveField(
            model_name='result',
            name='variant_ru',
        ),
        migrations.RemoveField(
            model_name='result',
            name='variant_uz',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject_uz',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='subject_uz',
        ),
    ]
