# Generated by Django 5.0 on 2023-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0008_variant_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Variant title'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Variant title'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Variant title'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Variant title'),
        ),
    ]
